#Create services for PostgreSQL and Redis

services: 
  postgres:
    image: postgres:16-alpine
    container_name: nodepress-postgres
    ports: 
      - "5432:5432"  # Expose PostgreSQL port
    environment: 
      POSTGRES_USER: nodepress
      POSTGRES_PASSWORD: nodepress123
      POSTGRES_DB: nodepress
    volumes: 
      - postgres_data:/var/lib/postgresql/data # Persist Data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: nodepress-redis
    ports: 
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: